# Generated by Django 4.0.4 on 2022-04-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newuser',
            fields=[
                ('User_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
    ]
