# Generated by Django 3.0.8 on 2022-04-17 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Departmnet_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Departmentname', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('Visitor_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Visitor_Name', models.CharField(max_length=225)),
                ('Visitor_CNIC', models.CharField(max_length=15)),
                ('Visitor_Mobile', models.CharField(max_length=15)),
                ('Visitor_Company', models.CharField(max_length=150)),
                ('Visitor_Address', models.CharField(max_length=150)),
                ('Meeting_With', models.CharField(max_length=15)),
                ('Check_In', models.DateTimeField()),
                ('Check_Out', models.DateTimeField()),
                ('Purpose_Of_Meeting', models.CharField(max_length=15)),
                ('Department_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='visitor.Department')),
            ],
        ),
    ]
