# Generated by Django 3.0.8 on 2022-04-19 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='Departmentname',
            new_name='Department_Name',
        ),
    ]
