# Generated by Django 3.0.8 on 2022-04-19 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_auto_20220419_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='Departmnet_ID',
            new_name='Departmen_ID',
        ),
    ]
