# Generated by Django 3.0.8 on 2022-04-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0004_auto_20220419_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='Visitor_ID',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
